import html2canvas from "html2canvas";
import jsPDF from "jspdf";

// Renders the DOM node `elementId` to a canvas and produces a multi-page A4 PDF.
export async function exportElementAsPDF(elementId, filename = "report.pdf") {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Report element not found.");

  const canvas = await html2canvas(element, { scale: 2, backgroundColor: "#ffffff", useCORS: true });
  const imgData = canvas.toDataURL("image/png");

  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = 0;
  let page = 1;
  const totalPages = Math.ceil(imgHeight / pageHeight);

  pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
  addFooter(pdf, page, totalPages, pageWidth, pageHeight);
  heightLeft -= pageHeight;

  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    page += 1;
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
    addFooter(pdf, page, totalPages, pageWidth, pageHeight);
    heightLeft -= pageHeight;
  }

  pdf.save(filename);
}

function addFooter(pdf, page, totalPages, pageWidth, pageHeight) {
  pdf.setFontSize(8);
  pdf.setTextColor(120);
  pdf.text(`Page ${page} of ${totalPages}`, pageWidth - 25, pageHeight - 6);
  pdf.text("Generated by Hindustan Besan Mill Management System", 8, pageHeight - 6);
}

// Downloads the DOM node as a PNG or JPG image, suitable for WhatsApp/sharing.
export async function exportElementAsImage(elementId, filename = "report.png", type = "png") {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Report element not found.");

  const canvas = await html2canvas(element, { scale: 2, backgroundColor: "#ffffff", useCORS: true });
  const mime = type === "jpg" ? "image/jpeg" : "image/png";
  const dataUrl = canvas.toDataURL(mime, 0.95);

  const link = document.createElement("a");
  link.href = dataUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
